Update requirements.txt
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
python-telegram-bot 13.15 requires cachetools==4.2.2, but you have cachetools 5.3.3 which is incompatible.
python-telegram-bot 13.15 requires tornado==6.1, but you have tornado 6.4 which is incompatible.